import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import ReactQueryProvider from "../react-query/index"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manRope = Manrope({
    subsets : ["latin"],
    weight : "200"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={`${manRope.className} antialiased`}
            >
            <ReactQueryProvider>
                {children}
            </ReactQueryProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
